### ISSUE TITLE
README could contain display resolution instructions

### ISSUE THREAD

**Issue by GreyGnome** [patrikolausson/dispmanx_vnc#1]
Hi,
Thanks for this software! It works a treat on a Raspberry Pi B model 2, with OSMC_TGT_rbp2_20151027.img.gz (based on Jessie, I believe).

One suggestion: In the README, put instructions on modifying the screen resolution. It's 720x480 out of the box. I went here: http://raspmer.blogspot.com/2015/07/vnc-server-for-raspberry-pi-with.html and here: https://www.raspberrypi.org/documentation/configuration/config-txt.md to figure out what to do. These are the settings I used in the /boot/config.txt:
```
#HDMI force hotplug
hdmi_force_hotplug=1
# Group DMT
hdmi_group=2
# mode 39 - 1360x768    60Hz
hdmi_mode=39
```
I rebooted after changing the file.

So note that this means you use the DMT table. Also, a higher sceen resolution means fewer frames per second. 

Finally, note that you must remove the lines and reboot if you want to plug in a real screen.

**Comment by patrikolausson** [comment]
Added a Screen resolution / Headless operation section to the readme file
