### ISSUE TITLE
Server runs, connection happens... but does not connect.

### ISSUE THREAD

**Issue by madeofpeople** [patrikolausson/dispmanx_vnc#2]
I'm on OSMC
built using the instructions in the readme... 
and when i run the server everything seems legit,
but alas nothing but spinners when i try to connect from my client... 

Heres the output from `sudo ./dispmanx_vncserver`

`
trying: /etc/dispmanx_vncserver.conf
No config file found
Running vnc server with the following settings
  frame-rate = 15
  downscale = false
  fullscreen = false
  multi-threaded = false
  password = 
  port = 0
  relative = false
  screen = 0
  unsafe = false
Open display[0]...
info: 640, 480, 0, 0
Display is 640 x 480
Server bpp:16
Server bigEndian:0
Server redShift:0
Server blueShift:10
Server greeShift:5
24/02/2016 17:42:23 Listening for VNC connections on TCP port 5900
24/02/2016 17:42:23 Listening for VNC connections on TCP6 port 5900
open /dev/uinput returned 7.
First write returned 1116.
ioctl UI_DEV_CREATE returned 0.
24/02/2016 17:44:23 Got connection from client 192.168.0.102
24/02/2016 17:44:23   other clients:
24/02/2016 17:44:23 Normal socket connection
Open display[0]...
info: 640, 480, 0, 0
Display is 640 x 480
24/02/2016 17:44:23 Client Protocol Version 3.3           
24/02/2016 17:44:23 Protocol version sent 3.3, using 3.3
24/02/2016 17:44:26 rfbProcessClientInitMessage: client gone
24/02/2016 17:44:26 Client 192.168.0.102 gone
24/02/2016 17:44:26 Statistics             events    Transmit/ RawEquiv ( saved)
24/02/2016 17:44:26  TOTALS              :      0 |         0/        0 (  0.0%)
24/02/2016 17:44:26 Statistics             events    Received/ RawEquiv ( saved)
24/02/2016 17:44:26  TOTALS              :      0 |         0/        0 (  0.0%)
24/02/2016 17:44:26 Got connection from client 192.168.0.102
24/02/2016 17:44:26   other clients:
24/02/2016 17:44:26 Normal socket connection
Open display[0]...

`

**Comment by patrikolausson** [comment]
From the log it seems like the vnc client disconnects. Which vnc client are you using?

**Comment by vrtlspd** [comment]
I'm using ultra VNC
http://www.uvnc.com/downloads/ultravnc.html

**Comment by patrikolausson** [comment]
In the log on the issue it says "Client Protocol Version 3.3", in my log I get  "Client Protocol Version 3.8" when using both UltraVNC and RealVNC. May be worth a try to use another or a newer viewer.

**Comment by madeofpeople** [comment]
“Screen Sharing” on OSX.

**Comment by patrikolausson** [comment]
Ok, tried OSX Screen Sharing now, and it works for me. It negotiates client protocol version 3.3, like yours, but it works. I am using Screen Sharing version 1.7 (492.38). Maybe try to upgrade if not on latest, or try another VNC client.

**Comment by patrikolausson** [comment]
Not able to reproduce
