### ISSUE TITLE
Inverted 'Y'

### ISSUE THREAD

**Issue by davelawr** [patrikolausson/dispmanx_vnc#4]
running dispmanx_vnc on a RPi (model 3B) using the official 800x480 touchscreen, the Y-axis mouse coordinates are inverted. adding in y = info.height - y into DoPtr() resolves this.

here is a a patch to add a '--flip-y' command line and configuration option:

[flipy.patch.txt](https://github.com/patrikolausson/dispmanx_vnc/files/474874/flipy.patch.txt)

**Comment by patrikolausson** [comment]
Would you mind testing the latest version without the flip code? I have changed the way the mouse and keyboard devices are opened to allow for them to be detected as standard keyboard and mouse instead of a touch screen.

**Comment by patrikolausson** [comment]
Closing issue. If the latest version does not work please create a new one and I will add your flip-code.
