### ISSUE TITLE
Missing /dev/input event node for VNC mouse input

### ISSUE THREAD

**Issue by ruvindad** [patrikolausson/dispmanx_vnc#5]
I noticed that when I start dispmanx_vnc it creates an "event" node on /dev/input for the keyboard and a "mouse" node for the mouse. 
However, when I plug in a physical mouse it creates both an "event" and a "mouse" node for the mouse.
Is there any reason why dispmanx_vnc doesn't also create an event node for the mouse?

I am asking because OpenFrameworks explicitly looks for an event node for the mouse, and thus I am unable to pass my vnc clients cursor to OpenFrameworks apps via dispmanx_vnc.

**Comment by patrikolausson** [comment]
Please check the latest commit and let me know if that helped.
